
### Electro-Magnetic Field (force caused by potential)

- static: lovslized source charge at rest, only spacial dependency, no time dependency
- stationary: source charce at uniform movement, steady current flow, space and time dependency
- dynamic: source charge at fast movement, radiation, space and time dependency
- relativistc: source charge at very speedy movement, radiation, space and time dependency

\

- rest localization vs. time-dependency
- slow vs. fast movemnt
- vacuum vs. matter
- local vs. global of $\mathscr{B}$, singularity vs. regularity of $\mathscr{E}$
- macro vs. micro
- far-field vs. near-field

\

#### Magnetic Field in Vacuum

$$\begin{split} &
\mathscr{B} = \nabla \times \boldsymbol{U_m} \coloneqq rot(A)
\newline &
\stackrel{\textnormal{Matter}}{=}
\mu_0 \left( \mathscr{H} + \mathscr{M} \right) 
\newline &
\stackrel{\textnormal{Vacuum}}{=} 
\frac{1}{c} \left( \frac{r}{\left| r \right|} \times \mathscr{E} \right)
\newline &
\stackrel{\textnormal{Far Field}}{=}
\frac{1}{2} \frac{1}{2\pi} \mu_0 \frac{k^2 e^{i(kr - \omega t)}}{r} \frac{r}{\left| r \right|} \times \left( c p_{0_{dipol}} + m_{0_{dipol}} \times \frac{r}{\left| r \right|} \right)
\newline &
\stackrel{\textnormal{Near Field}}{\approx}
\frac{1}{2} \frac{1}{2\pi} \mu_0 q \frac{v \times r}{\left| r \right|^2}
\approx
\frac{1}{2} \frac{1}{2\pi} i k c \mu_0 \frac{ \frac{r}{\left| r \right|} \times p_m}{r^2}
\end{split}$${#eq-mfield}

#### Magnetic Field in Matter
Exitation $\hat{=}$ Displacement
$$\begin{split} &
\text{Exication:} \qquad
\mathscr{H} = \frac{1}{\mu_0}\mathscr{B} - \mathscr{M} = \frac{1}{\mu}\mathscr{B} 
\newline &
\text{Magnetisation:} \qquad
\mathscr{M} = \frac{\mu - \mu_0}{\mu\mu_0}\mathscr{B} = \frac{\mu - \mu_0}{\mu_0}\mathscr{H}
\end{split}$${#eq-hfield}


#### Electric Field in Vacuum

$$\begin{split} &
\mathscr{E}
\stackrel{\textnormal{conservativ}}{=}
-\nabla U_e
\stackrel{\textnormal{dynamic}}{=}
-\nabla U_e - \frac{\partial}{\partial t} \boldsymbol{U_m}
\newline &
\stackrel{\textnormal{fast moving charge}}{=}
\newline &
\frac{1}{2} \frac{1}{2\pi} \frac{1}{\varepsilon_0} \frac{1}{r} \frac{1}{\left( 1 - \frac{r}{\left| r \right|} \cdot \frac{v}{c} \right)^3 } q 
\left[ 
\underbrace{
\left( 1 - \frac{v^2}{c^2} \right) \frac{\frac{r}{\left| r \right|} - \frac{v}{c}}{r} 
}_\text{uniform movement}
+ 
\underbrace{
    \frac{\frac{r}{\left| r \right|} \times \left[ \left( \frac{r}{\left| r \right|} - \frac{v}{c} \right) \times \dot{v} \right]
}{c^2} 
}_\text{accelerated movement}
\right]
\newline &
\stackrel{\textnormal{Far Field}}
= c \mathscr{B} \times \frac{1}{\left| r \right|}
\newline &
\stackrel{\textnormal{Near Field}}
\approx
\frac{1}{2} \frac{1}{2\pi} \frac{1}{\varepsilon_0} q \frac{r}{\left| r \right|^3}
\approx
\frac{1}{2} \frac{1}{2\pi} \frac{1}{\varepsilon_0} \frac{ 3 \frac{r}{\left| r \right|} \cdot p_m \frac{r}{\left| r \right|} - p_m}{r^3}
\end{split}$${#eq-efield}



#### Electric Field in Matter
Displacement $\hat{=}$ Exitation (field change) \
dielectricum = non-conducting material \
electricum = conductor medium

$$\begin{split} &
\text{Exication:} \qquad
\mathscr{D} = \varepsilon_0 \mathscr{E} + \mathscr{P} = 
\newline &
\stackrel{\textnormal{isotropic medium in weak fields}}{=}
\newline &
\varepsilon_0 \mathscr{E} + \varepsilon_0 \mbox{\Large$\chi$} \mathscr{E} = 
\varepsilon_0 \left( 1 + \mbox{\Large$\chi$}  \right) \mathscr{E} = 
\newline &
\varepsilon_0 4\pi r^3 n \left< p_m \right> = 
4\pi r^3 n \varepsilon_0 \left< \mathscr{E}_m \right> = 
\alpha n \varepsilon_0 \bar{\mathscr{E}}_m = 
\varepsilon \mathscr{E}
\newline &
\text{Polarisation:} \qquad
\mathscr{P} = \left( \varepsilon - \varepsilon_0 \right) \mathscr{E}
\end{split}$${#eq-dfield}


#### Abbreviations

$$
\Phi = \text{electric potential} \qquad 
A = \text{magnetic potential} \qquad 
j = \nabla \times \mathscr{H} = \text{elec. current density}
$$\linebreak$$
\mathscr{E} = \text{Electric Field} \qquad
\mathscr{B} = \text{Magnetic Field}     \qquad      \nabla \cdot \mathscr{B} = 0    \qquad
\mathscr{D} = \text{Displacement density of dielectricum} \qquad
\mathscr{M} = \text{magnetisation density}
$$\linebreak$$
\mathscr{P} = \text{Polarisation} \qquad
\mathscr{H} = \text{magn. exitation, magn. field strength ("magn. displacement")}  \qquad
$$\linebreak$$ 
n = \text{spacial molecule density in volume}
$$\linebreak$$ 
\alpha = 4\pi r^3 = constant     \qquad
\mbox{\Large$\chi$} = \text{elec. susceptibility of dieelectricum}    \qquad
\kappa = \frac{\mu - \mu_0}{\mu_0} = \text{magn. susceptibility} 
$$\linebreak$$ 
\left< p_m \right> = \text{spacial average of magn. dipol moment} \qquad
\left< \mathscr{E}_m \right> = \text{spacial average of electric field}  
$$\linebreak$$ 
\bar{\mathscr{E}}_m = \text{time average of electric field} \qquad
\mu = \text{magn. permeability} \qquad
\mu_0 = \text{magn. constant ...}
$$\linebreak$$ 
\varepsilon = \text{dielectricity constant} \qquad
\varepsilon_0 = \text{...}
$$
